### ISSUE TITLE
Joystick not start after instalation

### ISSUE THREAD

**Issue by christianolucas** [mitre-attack/joystick#7]
root@kali:/home/volt# git clone --recursive https://github.com/mitre-attack/joystick.git
Cloning into 'joystick'...
remote: Enumerating objects: 153, done.
remote: Counting objects: 100% (153/153), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 153 (delta 55), reused 147 (delta 49), pack-reused 0
Receiving objects: 100% (153/153), 1.04 MiB | 1.61 MiB/s, done.
Resolving deltas: 100% (55/55), done.
root@kali:/home/volt# cd joystick/
root@kali:/home/volt/joystick# pip3 install -r requirements.txt 
Requirement already satisfied: aiohttp_jinja2 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: pyaml in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (20.4.0)
Requirement already satisfied: pandas in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (0.25.3)
Requirement already satisfied: jinja2>=2.10.1 in /usr/local/lib/python3.8/dist-packages (from aiohttp_jinja2->-r requirements.txt (line 1)) (2.10.3)
Requirement already satisfied: aiohttp>=3.2.0 in /usr/lib/python3/dist-packages (from aiohttp_jinja2->-r requirements.txt (line 1)) (3.6.2)
Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from pyaml->-r requirements.txt (line 2)) (5.3.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from jinja2>=2.10.1->aiohttp_jinja2->-r requirements.txt (line 1)) (1.1.1)
root@kali:/home/volt/joystick# python joystick.py 
  File "joystick.py", line 24
    async def init(address, port, services):
            ^
SyntaxError: invalid syntax
root@kali:/home/volt/joystick#

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
